name: Build
run-name: ${{github.actor}} ${{github.branch}} | Build
on:
  push:
    branches:
      - "**"

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - name: Use Node.js
        uses: actions/setup-node@v4.0.3
        with:
          node-version: "20.13.1"

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build
